---
title: "ggplot-theme"
author: "hung"
date: '2022-07-22'
output: html_document
---

## lib

```{r library, message=FALSE}
library(tidyverse)
library(data.table)
library(openxlsx)
```

## set-up wd

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/hung/Data/side-project/misc-Rpackage/")
```

## create a df to plot

```{r}
df <- ToothGrowth %>%
  mutate(dose=as.factor(dose))
```

## plot with theme

```{r}
p <- ggplot(df, aes(x=dose, y=len, group=dose, color=dose)) +
  geom_boxplot()
#
p + theme(text=element_text(family="sans", size=6),
        panel.background=element_rect(fill=NA),
        panel.border=element_rect(fill=NA, size=0.25, color="black"),
        panel.grid=element_line(size=0.1, color="grey75"),
        legend.key.size=unit(c(9,9), "points"),
        legend.key = element_rect(fill=NA)
        )
```

## test function

```{r}
theme_misc <- function() {
  ggplot2::theme(text=element_text(family="sans", size=6),
        panel.background=element_rect(fill=NA),
        panel.border=element_rect(fill=NA, size=0.25, color="black"),
        panel.grid=element_line(size=0.1, color="grey75"))
}
#
p + theme_misc()
```


